<?php

use function Livewire\Volt\{title};

title('Handwerksrolle Online');

?>

<x-intranet-app-hwro::hwro-layout heading="Handwerksrolle Online" subheading="Verwaltung der Handwerksrolle">
    {{-- Index content is automatically generated by the layout --}}
</x-intranet-app-hwro::hwro-layout>